services:
  app-prod:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - '3000:3000'

  app-dev:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - TEST_KEYCLOAK_USERNAME
      - TEST_KEYCLOAK_PASSWORD
      - AUTH_KEYCLOAK_ID
      - AUTH_KEYCLOAK_SECRET
      - AUTH_KEYCLOAK_ISSUER
      - AUTH_SECRET="MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI="
      - AUTH_URL=http://localhost:3000/auth
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next